BUG: Fix Docker startup errors
The .jupyter directory does not exist in the Docker image.

This was the error output:

Generating a 2048 bit RSA private key
......................................................+++
.+++
writing new private key to '/root/.jupyter/jupyter.key'
/root/.jupyter/jupyter.key: No such file or directory
[...]
self.ssl_options['certfile'])
ValueError: certfile "/root/.jupyter/jupyter.pem" does not exist