MAINT: Provides better error message when QUANDL_API_KEY is missing
Quandl's new API for the WIKI Prices dataset requires an API key.
Omitting the API key when running 'zipline ingest' would cause:
HTTPError: HTTP Error 400: Bad Request

QUANDL_API_KEY is now checked at the start of the
ingestion process, and an error is raised if its value is 'None'.