BUG: Fix reference to floating type.
Use float64_t instead, since `isnan` is only used when the array's
dtype kind is `'f'`.

Fixes this compilation error:
```
zipline/pipeline/loaders/blaze/_core.pyx:30:16: 'floating' is not a type identifier
```